language: node_js

node_js:
  - 'node'
  - 'lts/*'
  - 8
  - 7
  - 6

install:
  - npm install

scripts:
  - npm ci

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
